import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main>
        <h2 className='text-2xl mt-10'>
          Upgrading your web development today.
        </h2>
        <h3>Learn web development using the latest technology!</h3>
      </main>
    </>
  );
}
